# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HotosmUtils
                                 A QGIS plugin
 Data analysis tools for HOTOSM disaster mapping work
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-04-03
        copyright            : (C) 2020 by Jarmo Kivekäs
        email                : jarmo.kivekas@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Jarmo Kivekäs'
__date__ = '2020-04-03'
__copyright__ = '(C) 2020 by Jarmo Kivekäs'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HotosmUtils class from file HotosmUtils.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .hotosm_utils import HotosmUtilsPlugin
    return HotosmUtilsPlugin()
